// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"context"
	"fmt"

	"github.com/ciscoecosystem/aci-go-client/v2/client"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/list"
	"github.com/hashicorp/terraform-plugin-framework/list/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ list.ListResource = &FvTenantListResource{}
var _ list.ListResourceWithConfigure = &FvTenantListResource{}

func NewFvTenantListResource() list.ListResource {
	return &FvTenantListResource{}
}

type FvTenantListResource struct {
	client *client.Client
}

type FvTenantListResourceModel struct {
	Filter types.String `tfsdk:"filter"`
}

func (r *FvTenantListResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	tflog.Debug(ctx, "Start metadata of list resource: aci_tenant")
	resp.TypeName = req.ProviderTypeName + "_tenant"
	tflog.Debug(ctx, "End metadata of list resource: aci_tenant")
}

func (r *FvTenantListResource) ListResourceConfigSchema(ctx context.Context, req list.ListResourceSchemaRequest, resp *list.ListResourceSchemaResponse) {
	tflog.Debug(ctx, "Start schema of list resource: aci_tenant")
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"filter": schema.StringAttribute{
				Description: "The filter that should be applied to the query.",
				Optional:    true,
			},
		},
	}
	tflog.Debug(ctx, "Start schema of list resource: aci_tenant")
}

func (r *FvTenantListResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	tflog.Debug(ctx, "Start configure of list resource: aci_tenant")

	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected List Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
	tflog.Debug(ctx, "End configure of list resource: aci_tenant")
}

func (r *FvTenantListResource) List(ctx context.Context, req list.ListRequest, stream *list.ListResultsStream) {

	var configData FvTenantListResourceModel

	var diags diag.Diagnostics
	diags.Append(req.Config.Get(ctx, &configData)...)
	if diags.HasError() {
		return
	}

	path := "api/node/class/fvTenant.json"
	if !configData.Filter.IsNull() {
		path = fmt.Sprintf("%s?%s", path, configData.Filter.ValueString())
	}

	requestData := DoRestRequest(ctx, &diags, r.client, path, "GET", nil)

	stream.Results = func(push func(list.ListResult) bool) {
		if requestData.Search("imdata").Search("fvTenant").Data() != nil {
			for _, managedObject := range requestData.Search("imdata").Search("fvTenant").Data().([]interface{}) {
				result := req.NewListResult(ctx)
				attributeMap := managedObject.(map[string]interface{})["attributes"].(map[string]interface{})
				result.Identity.Set(ctx, FvTenantIdentityModel{Id: basetypes.NewStringValue(getStringValueFromMap("dn", attributeMap))})
				fvTenant := getEmptyFvTenantResourceModel()
				fvTenant.Annotation = basetypes.NewStringValue(getStringValueFromMap("annotation", attributeMap))
				fvTenant.Descr = basetypes.NewStringValue(getStringValueFromMap("descr", attributeMap))
				fvTenant.Name = basetypes.NewStringValue(getStringValueFromMap("name", attributeMap))
				fvTenant.NameAlias = basetypes.NewStringValue(getStringValueFromMap("nameAlias", attributeMap))
				fvTenant.OwnerKey = basetypes.NewStringValue(getStringValueFromMap("ownerKey", attributeMap))
				fvTenant.OwnerTag = basetypes.NewStringValue(getStringValueFromMap("ownerTag", attributeMap))
				diags.Append(result.Resource.Set(ctx, fvTenant)...)
				if diags.HasError() {
					return
				}
				if !push(result) {
					return
				}
			}
		}
	}
}

func getStringValueFromMap(key string, attributeMap map[string]interface{}) string {
	if value, ok := attributeMap[key]; ok {
		return value.(string)
	}
	return ""
}
